### ISSUE TITLE
Mouseover icon getting stuck on first mouseover target

### ISSUE THREAD

**Issue by Jbleedge** [Choonster-WoW-AddOns/TargetNameplateIndicator#1]
I tried today to use this addon.

The first mouseover icon gets stuck on the target so if I mouseover something else it doesn't work.
If I set the focus it doesn't set any icon.
Also: Where do I change the mouseover icon to be different than the target one?

Do you plan to add a small ingame menu aswell in the future?

Thanks

**Comment by Choonster** [comment]
I'll look into the issue next weekend.

At the moment you can only have separate textures based on the unit's reaction type (self, friendly or hostile), you can't have separate textures for your target, mouseover and focus.

I probably won't add an in-game menu as they're a bit annoying to make.

**Comment by Choonster** [comment]
I can't reproduce this issue with the default nameplates. Are you using a nameplate AddOn?

**Comment by Jbleedge** [comment]
At the time I opened the issue I was using default ElvUI one.
Now I'm using KUI, but if I have the same icon for target, mouseover and focus it's not that helpful

**Comment by Choonster** [comment]
I just released version 1.28 earlier, which adds a separate config file for each unit. This means you can now configure each unit to use a different set of self, friendly and hostile textures.

**Comment by Choonster** [comment]
ElvUI nameplates don't work properly with TNI, see [this comment thread](https://www.curseforge.com/wow/addons/targetnameplateindicator?comment=140) on CurseForge.

**Comment by Jbleedge** [comment]
Cool, I'll try it :) Thank you!

**Comment by Choonster** [comment]
I added a config GUI in 1.29 (released on 2018-08-19), and ElvUI fixed the issue on 2018-10-11 (though I didn't notice until 2019-08-24).
