### ISSUE TITLE
Errors popping up when friendly nameplates are enabled

### ISSUE THREAD

**Issue by Aquastias** [Choonster-WoW-AddOns/TargetNameplateIndicator#2]
The following error I captured with BugSack when I activated the friendly nameplates:

> 109x TargetNameplateIndicator\core.lua:146: Usage: UnitIsUnit("unit", "otherUnit")
> [C]: in function `UnitIsUnit'
> TargetNameplateIndicator\core.lua:146: in function <TargetNameplateIndicator\core.lua:144>
> 
> Locals:
> (*temporary) = "mouseover"
> (*temporary) = nil

**Comment by Choonster** [comment]
Are you using ElvUI nameplates? They don't work properly with TNI, see [this comment thread](https://www.curseforge.com/wow/addons/targetnameplateindicator?comment=140) on CurseForge.

**Comment by Aquastias** [comment]
Yes I'm using ElvUI and I've read the thread. Thanks for the fast response. I hope the ElvUI team will support your addon.
