### ISSUE TITLE
Update for Dragonflight?

### ISSUE THREAD

**Issue by xapollyon** [Choonster-WoW-AddOns/TargetNameplateIndicator#4]
- Any updates for Dragonflight?
- can we add our own target icons into this?

**Comment by Choonster** [comment]
I haven't tested this with Dragonflight. Does it work, or are there errors? I'll have a look on the weekend.

You can set custom textures for each indicator in the options menu.

**Comment by xapollyon** [comment]
> I haven't tested this with Dragonflight. Does it work, or are there errors? I'll have a look on the weekend.
> 
> You can set custom textures for each indicator in the options menu.

Wow, that was the fastest reply ever.

Yea seems to work, might need a TOC update

**Comment by Choonster** [comment]
I've released 1.46, which bumps the TOC Interface version to 10.0.0. No other changes seemed to be required.
