### ISSUE TITLE
Classic Era Update 1.15.1

### ISSUE THREAD

**Issue by maximus210793** [Choonster-WoW-AddOns/TargetNameplateIndicator#5]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game  Version of 1.15.1?
Would be awesome, thanks a lot in advance!

**Comment by Choonster** [comment]
I've just released version 1.54, which bumps the TOC Interface versions for Retail and Classic Era.

I'm glad you're enjoying the AddOn, let me know if you find any issues.
