### ISSUE TITLE
WoW Classic Era Update - Version 1.15.2

### ISSUE THREAD

**Issue by maximus210793** [Choonster-WoW-AddOns/TargetNameplateIndicator#6]
Hi,
Could you update it to the latest Classic Era Game  Version of 1.15.2?
Would be awesome, thanks a lot in advance!

**Comment by Choonster** [comment]
I've just released version [1.55](https://github.com/Choonster-WoW-AddOns/TargetNameplateIndicator/releases/tag/1.55), which bumps the TOC Interface versions for Retail, Classic and WotLK Classic.
