### ISSUE TITLE
WoW Classic Era Update - Version 1.15.4

### ISSUE THREAD

**Issue by maximus210793** [Choonster-WoW-AddOns/TargetNameplateIndicator#9]
Hi,

Could you update it to the latest Classic Era Game  Version of 1.15.4?

Would be awesome, thanks a lot in advance!

**Comment by Choonster** [comment]
I've released version 1.57, which bumps the TOC version for 11.0.2 and 1.15.4. I can't test it on Classic myself, but it doesn't look like there should be any changes required.

Let me know if you get any issues.
